PubkeyAuthentication yes
StrictModes yes
PasswordAuthentication no
KbdInteractiveAuthentication no
AuthenticationMethods publickey
AuthorizedKeysFile /etc/ssh/authorized_keys/%u
PermitEmptyPasswords no
PermitRootLogin no
UsePAM yes
X11Forwarding no
